/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 69c383bb43aac68fce4569c6fc7ed800)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	NODE_ENV: string;
	NEXT_INC_CACHE_R2_PREFIX: string;
	WORKER_SELF_REFERENCE: Fetcher /* rowdyhacks-xii-web */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<Cloudflare.Env, "NODE_ENV" | "NEXT_INC_CACHE_R2_PREFIX">
		> {}
}
